formation/urls.py
from django.urls import path
from formation.models import Formation
from formation.views import(

		create_formation_view,
		detail_formation_view,
		edit_formation_view,
		search,
		
		

	)

app_name = 'formation'

urlpatterns =[

path('create/' , create_formation_view, name="create"),
path('<slug>/' ,detail_formation_view, name="detail"),
path('<slug>/edit/' ,edit_formation_view, name="edit"),
path('search/', search, name='search'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
    
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
    
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('formation/', include('formation.urls','formation')), 
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

formation/models.py
from django.db import models
from django.utils.text import slugify
import uuid
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

#Two tuple structure
#The first element in each tuple is the value that will be stored in the database. The second element is displayed by the field’s form widget.
#Tuple
ETAT = [
	('Active', 'Active'), #Tuple1
	('Non Active', 'Non Active'), #Tuple2
	
]
TYPES = [
	('JAVA', 'JAVA'), #Tuple1
	('HTML', 'HTML'), #Tuple2
	
]

class Formation(models.Model):
	title		 			= models.CharField(max_length=60)
	logo 					= models.ImageField(upload_to='images/')
	etat 					= models.CharField(max_length=10, choices=ETAT)
	types 					= models.CharField(max_length=10, choices=TYPES)
	slug 					= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title


	class Meta:
		verbose_name = 'Formation'
		verbose_name_plural = 'Formation chez GTA'

@receiver(post_delete, sender=Formation)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=Formation)

formation/forms.py
from django import forms

from formation.models import Formation

class CreateFormationForm(forms.ModelForm):

	class Meta:
		model = Formation
		fields = ['title','logo' ,'etat']



class UpdateFormationPostForm(forms.ModelForm):

	class Meta:
		model = Formation
		fields = ['title', 'logo', 'etat']

		def save(self, commit=True):
			formation_posts = self.instance
			formation_posts.title = self.cleaned_data['title']
			formation_posts.etat = self.cleaned_data['etat']

			if self.cleaned_data['logo']:
				formation_posts.logo = self.cleaned_data['logo']

			if commit:
				formation_posts.save()
			return formation_posts

formation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from formation.models import Formation
from account.models import Account
from formation.forms import CreateFormationForm, UpdateFormationPostForm
from personal.filters import OrderFilter



def create_formation_view(request):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	form = CreateFormationForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		 
		obj.save()
		form = CreateFormationForm()
	context['form'] = form



	return render(request, "formation/create_formation.html", context)


def detail_formation_view(request, slug):

	context = {}

	formation_posts = get_object_or_404(Formation, slug=slug)

	context['formation_posts'] = formation_posts


	return render (request, 'formation/detail_formation.html', context)


def edit_formation_view(request, slug):


	context = {}

	user = request.user

	if not user.is_authenticated:
		return redirect("must_authenticate")

	formation_posts = get_object_or_404(Formation, slug=slug)
	if request.POST:
		form = UpdateFormationPostForm(request.POST or None, request.FILES or None, instance=formation_posts)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			formation_posts = obj

	form = UpdateFormationPostForm(
			initial = {

					"title": formation_posts.title,
					"etat": formation_posts.etat,
					"logo": formation_posts.logo,
			}



		)

	context['form'] = form
	return render(request, 'formation/edit_formation.html', context)


def get_formation_queryset(query=None):
	queryset = []
	queries = query.split(" ")
	for q in queries:
		posts = Formation.objects.filter(
			Q(title__icontains=q)|
			Q(etat__icontains=q)

			).distinct()
		for post in posts:
				queryset.append(post)
	return list(set(queryset))




def search(request):
    user_list = Formation.objects.all()
    user_filter = OrderFilter(request.GET, queryset=user_list)
    return render(request, 'formation/detail_formation.html', {'filter': user_filter})

formation/templates/formation/create_formation.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_etat">Etat</label>
					<select class="form-control" rows="10" type="text" name="etat" id="id_etat" placeholder="This blog is about..." required>>
						<option>Active</option>
						<option>Non Active</option>

					</select>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_logo">Logo</label>
					<input  type="file" name="logo" id="id_logo" accept="image/*" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>




{% endblock content %}

formation/templates/formation/detail_formation.html
{% extends 'base.html' %}


{% block content %}


<style type="text/css">
	
	.card {

		max-width:  700px;
		max-height: 100px
	}

	.container{
		padding: :20px;
	}

</style>


<div class="container">

    
   
	<div class="row">
	<div>	  
  {% for formation_posts in filter.qs %}
  <label class="checkbox-inline">
    {{formation_posts.etat}}
  </label>
  {% endfor %}
</div>
  

		<div class="card m-auto">
			<img  class="card-img-top" src="{{formation_posts.logo.url}}">
			<div class="card-body my-2">
				<h2 class="card-title">{{formation_posts.title}}</h2>
				<p class="card-text">{{formation_posts.etat}}</p>
				{% if user.is_staff %}
				<a href="{% url 'formation:edit' formation_posts.slug %}" class="btn btn-primary"> Updates</a>
				{% endif %}
				
			</div>
			
				
		</div>
		

	</div>



 
</div>


{% endblock content%}

formation/templates/formation/edit_formation.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_etat">Etat</label>
					<select class="form-control" rows="10" type="text" name="etat" id="id_etat" placeholder="Etat Formation..." 
					required>{{form.initial.etat}}
					<option>Active</option>
					<option>Non Active</option>
				</select>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.logo.url}}" id="id_logo_display">
					  <div class="middle">
					    <div class="text">Change Logo</div>
					  </div>
				</div>
				<input type="file" name="logo" id="id_logo_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}