formation/urls.py
from django.urls import path
from formation.models import Formation
from formation.views import(

		create_formation_view,
		detail_formation_view,
		edit_formation_view,
		search,
		
		

	)

app_name = 'formation'

urlpatterns =[

path('create/' , create_formation_view, name="create"),
path('<slug>/' ,detail_formation_view, name="detail"),
path('<slug>/edit/' ,edit_formation_view, name="edit"),
path('search/', search, name='search'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
    home_screen_view,
    
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
    
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('formation/', include('formation.urls','formation')), 
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/models.py
from django.db import models

# etat =[
# ("Activé","activé"),
# ("Non Activé","non activé"),
# ]
# class Formation(models.Model):
# 	title					=models.CharField(max_length=60)
# 	logo					=models.CharField(max_length=60)
# 	etat					=models.CharField(max_length=10,choices=etat)

# 	def __str__(self):
# 		return self.title

# 	class Meta:
# 		verbose_name ="Formation"
# 		verbose_name_plural="Formation"

		

personal/views.py
from django.shortcuts import render
from formation.models import Formation
from formation.views import get_formation_queryset
from operator import attrgetter


# Create your views here.
def home_screen_view(request):

	  context = {}

	  query = ""
	  if request.GET:
	  	query = request.GET['q']
	  	context['query'] = str(query)


	  formation_posts = get_formation_queryset(query)
	  context['formation_posts'] = formation_posts


	  return render(request, "personal/home.html", context)
      

personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

     @media (max-width: 768px) { 
          .right-column{
               margin-left: 0px;
          }
     }

     @media (min-width: 768px) { 
          .right-column{
               margin-left: 20px;
          }
     }

     .blog-post-container{
          margin-bottom: 20px;
          width: 100%;
     }
     .create-post-bar{
          background-color: #fff;
          margin-bottom:20px;
     }

     .left-column{
          padding:0px;
     }

     .right-column{
          padding:0px;
     }
     .lead{
          font-size: 17px;
     }
</style>
<div class="container">
     <div class="row">

          <!-- formation feed -->
          <div class="left-column col-lg-7 offset-lg-1">

               <!-- Top 'create post' bar -->
               <div class="d-lg-none mb-3">
                    <div class="card m-auto d-flex flex-column p-3">
                         <img class="img-fluid d-block m-auto pb-2" src="{% static '1.png' %}" width="72" height="72">
                         <p class="lead">create a new training</p>
                         <p class="m-auto"><a class="btn btn-primary" href="{% url 'formation:create' %}">Create formation</a></p>
                    </div>
               </div>
               <!-- end Top 'create post' bar -->

               <!-- Formation posts-->

               {% if formation_posts %}
                    {% for post in formation_posts %}
                         <div class="blog-post-container">
                              {% include 'formation/snippets/formation_post_snippet.html' with formation=post %}
                         </div>
                    {% endfor %}
               {% else %}
                    <div class="blog-post-container">
                         {% include 'formation/snippets/formation_post_snippet.html' with query=query %}
                         
                    </div> 
               {% endif %}
               <!-- End Formation posts-->
          </div>
          <!-- end Formation feed -->

          {% if user.is_authenticated and user.is_superuser %}
          <!-- Right 'create post' column  -->
          <div class="right-column col-lg-3 d-lg-flex d-none flex-column">

               <div class="card create-post-bar d-flex flex-column p-3">
                    <img class="img-fluid d-block m-auto pb-2" src="{% static '1.png' %}" width="72" height="72">
                    <p class="lead">You can create a new training</p>
                  
                    <p class="m-auto"><a class="btn btn-primary" href="{% url 'formation:create' %}">Create </a></p>

               </div>
          
          </div>
           {% endif %}
          <!-- end Right 'create post' column  -->

     </div>
</div>

{% endblock content %}